# Generated by Django 5.1.6 on 2025-02-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.CharField(max_length=100)),
                ('rd', models.TextField()),
                ('ri', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
